name: Deploy to stockup.gt.tc

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to stockup.gt.tc
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_40223287
          password: O2MvS69Qqs1
          server-dir: /htdocs/
          timeout: 86400000 # 24 hours in milliseconds
          log-level: standard